---
platform: linux

image_resource:
  type: docker-image
  source: {repository: docker, tag: dind}

inputs:
- name: resource-haproxy

outputs:
- name: web-docker-image

run:
  path: ./resource-haproxy/.concourse/tasks/build-haproxy-container.sh
