---
platform: linux

image_resource:
  type: docker-image
  source: {repository: docker, tag: dind}

inputs:
- name: web-docker-image
- name: resource-personal_website

run:
  path: resource-personal_website/.concourse/tasks/load-web-container.sh
